### ISSUE TITLE
ckeditor

### ISSUE THREAD

**Issue by dijiudu** [r26zhao/django_blog#1]
博主，我参考了你的博客，结合这个仓库的源码，在调试 ckeditor时候 ，我的代码高亮+显示行数 功编辑时候有效，但是网页显示无效F12你的 网页发现
```
<script type="text/javascript" src="http://www.aaron-zhao.com/static/ckeditor/ckeditor/config.js?t=GB8C"></script>
<link rel="stylesheet" type="text/css" href="http://www.aaron-zhao.com/static/ckeditor/ckeditor/skins/moono-lisa/editor.css?t=GB8C">
```
很多类似代码js加载项，但是在这个仓库的html里面没有发现加载项，所以不清楚你是怎么解决这个问题的

**Comment by r26zhao** [comment]
代码高亮 显示行数 看这里http://www.aaron-zhao.com/post/1/#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE%E3%80%81%E4%BB%A3%E7%A0%81%E8%A1%8C%E6%95%B0%20%C2%A0
需要在前端引入静态文件

**Comment by dijiudu** [comment]
多谢提醒，现在已经正常显示了。还有个问题，我看到文章目录树使用正则匹配来处理，那么在后台使用 ckeditor 编辑文章时候 ，还需要些 特定的 html 代码才能被识别到吗？
